DELETE FROM TypeTags WHERE Type='ABILITY_TOMYRIS_BONUS_VS_WOUNDED_UNITS';

INSERT OR IGNORE INTO TypeTags (Type , Tag) VALUES
	('ABILITY_TOMYRIS_BONUS_VS_WOUNDED_UNITS' ,'CLASS_ALL_COMBAT_UNITS');

DELETE FROM TypeTags WHERE Type='ABILITY_MONTEZUMA_COMBAT_BONUS_PER_LUXURY';

INSERT OR IGNORE INTO TypeTags (Type , Tag) VALUES
	('ABILITY_MONTEZUMA_COMBAT_BONUS_PER_LUXURY' ,'CLASS_ALL_COMBAT_UNITS');

DELETE FROM TypeTags WHERE Type = 'ABILITY_TRAIT_MAPUCHE';

INSERT OR IGNORE INTO TypeTags
	(Type , Tag)
	VALUES
	('ABILITY_TRAIT_MAPUCHE' ,'CLASS_ALL_COMBAT_UNITS');