DELETE FROM TraitModifiers WHERE ModifierId = 'BBG_TRAIT_MALI_LESS_PRODUCTION';

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_CIVILIZATION_MALI_GOLD_DESERT', 'BBG_TRAIT_MALI_LESS_CITY_PRODUCTION'),
    ('TRAIT_CIVILIZATION_MALI_GOLD_DESERT', 'BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION_GIVER');

DELETE FROM Modifiers WHERE ModifierId = 'BBG_TRAIT_MALI_LESS_PRODUCTION';

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION_GIVER', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER'),
    ('BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION', 'MODIFIER_CITY_ADJUST_RESOURCE_HARVEST_BONUS'),
    ('BBG_TRAIT_MALI_LESS_CITY_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER');

DELETE FROM ModifierArguments WHERE ModifierId = 'BBG_TRAIT_MALI_LESS_PRODUCTION';

INSERT INTO INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_TRAIT_MALI_LESS_CITY_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('BBG_TRAIT_MALI_LESS_CITY_PRODUCTION', 'Amount', '-30');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION_GIVER', 'ModifierId', 'BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION'),
    ('BBG_TRAIT_MALI_LESS_CHOP_PRODUCTION', 'Amount', '-30');