INSERT OR IGNORE INTO TraitModifiers (TraitType , ModifierId)
	VALUES
	('TRAIT_CIVILIZATION_HELLENISTIC_FUSION' , 'TRAIT_CIVILIZATION_HELLENISTIC_FUSION_PRODUCTION_MODIFIER');
INSERT INTo Requirements(RequirementId, RequirementType) VALUES
	('MACEDON_RECENTLY_CONQUERED_BBG_REQ', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
	('MACEDON_RECENTLY_CONQUERED_BBG_REQ', 'PropertyName', 'GETS_MACEDON_20'),
	('MACEDON_RECENTLY_CONQUERED_BBG_REQ', 'PropertyMinimum', 1);
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
	('MACEDON_RECENTLY_CONQUERED_BBG_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
	('MACEDON_RECENTLY_CONQUERED_BBG_REQSET', 'MACEDON_RECENTLY_CONQUERED_BBG_REQ');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('TRAIT_CIVILIZATION_HELLENISTIC_FUSION_PRODUCTION_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'MACEDON_RECENTLY_CONQUERED_BBG_REQSET');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('TRAIT_CIVILIZATION_HELLENISTIC_FUSION_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
	('TRAIT_CIVILIZATION_HELLENISTIC_FUSION_PRODUCTION_MODIFIER', 'Amount', 20);