/*
-- Babylon don't get Eureka boost from Free Inquiry
INSERT INTO Types(Type, Kind) VALUES
    ('MODIFIER_SINGLE_PLAYER_ATTACH_MODIFIER', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers(ModifierType, CollectionType, EffectType) VALUES
    ('MODIFIER_SINGLE_PLAYER_ATTACH_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ATTACH_MODIFIER');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
    ('BBG_REQSET_PLAYER_IS_BABYLON', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
    ('PLAYER_IS_BABYLON', 'REQUIREMENT_PLAYER_TYPE_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('PLAYER_IS_BABYLON', 'CivilizationType', 'CIVILIZATION_BABYLON_STK');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('BBG_REQSET_PLAYER_IS_BABYLON', 'PLAYER_IS_BABYLON');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS_MODIFIER', 'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST', 'BBG_REQSET_PLAYER_IS_BABYLON');

INSERT INTO ModifierArguments(ModifierId, Name, Value, Extra) VALUES
    ('BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS_MODIFIER', 'Amount', '-10', '-1');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId) VALUES
    ('BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS', 'MODIFIER_SINGLE_PLAYER_ATTACH_MODIFIER', 'PLAYER_HAS_GOLDEN_AGE');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS', 'ModifierId', 'BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS_MODIFIER');

INSERT INTO CommemorationModifiers(CommemorationType, ModifierId) VALUES
    ('COMMEMORATION_SCIENTIFIC', 'BBG_COMMEMORATION_SCIENTIFIC_GA_BABYLON_ANTIBOOSTS');

----
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
    ('PLAYER_IS_NOT_BABYLON', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('PLAYER_IS_NOT_BABYLON', 'TraitType', 'TRAIT_CIVILIZATION_BABYLON');
*/
UPDATE Requirements SET RequirementType = 'REQUIREMENT_PLAYER_TYPE_MATCHES' WHERE RequirementId = 'PLAYER_IS_NOT_BABYLON';
UPDATE RequirementArguments SET Name = 'CivilizationType' AND Value = 'CIVILIZATION_BABYLON_STK' WHERE RequirementId = 'PLAYER_IS_NOT_BABYLON';
UPDATE Requirements SET Inverse = '1' WHERE RequirementId = 'PLAYER_IS_NOT_BABYLON';