--Remove old scaling through civics
DELETE FROM ModifierArguments WHERE ModifierId LIKE 'BBG_MODIFIER_MONKS_CS_%';
DELETE FROM ModifierArguments WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';
DELETE FROM Modifiers WHERE ModifierId LIKE 'BBG_MODIFIER_MONKS_CS_%';
DELETE FROM Modifiers WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';
DELETE FROM CivicModifiers WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';

--Revert Monk Scaling but as an ability
INSERT INTO Requirements(RequirementId, RequirementType)
	SELECT 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQUIREMENT' , 'REQUIREMENT_PLAYER_HAS_CIVIC'
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO RequirementArguments(RequirementId, Name, Value)
	SELECT 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQUIREMENT', 'CivicType', Civics.CivicType
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType)
	SELECT 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQSET', 'REQUIREMENTSET_TEST_ALL'
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId)
	SELECT 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQSET', 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQUIREMENT'
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
	SELECT 'BBG_MODIFIER_MONKS_CS_' || Civics.CivicType , 'MODIFIER_UNIT_ADJUST_BASE_COMBAT_STRENGTH', 'BBG_PLAYER_HAS_' || Civics.CivicType || '_REQSET'
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO ModifierArguments(ModifierId, Name, Value)
	SELECT 'BBG_MODIFIER_MONKS_CS_'|| Civics.CivicType , 'Amount', '1'
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId)
	SELECT 'BBG_ABILITY_MONK_SCALING', 'BBG_MODIFIER_MONKS_CS_'|| Civics.CivicType
	FROM Civics WHERE EraType IN ('ERA_ANCIENT','ERA_CLASSICAL', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL');