DELETE FROM ModifierArguments WHERE ModifierId LIKE 'BBG_MODIFIER_MONKS_CS_%';
DELETE FROM ModifierArguments WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';
DELETE FROM Modifiers WHERE ModifierId LIKE 'BBG_MODIFIER_MONKS_CS_%';
DELETE FROM Modifiers WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';
DELETE FROM CivicModifiers WHERE ModifierId LIKE 'BBG_ABILITY_MODIFIER_MONKS_%';