INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('ALEX_PRODUCTION_MODIFIER','MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('ALEX_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
	('ALEX_PRODUCTION_MODIFIER', 'Amount', '20');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('ALEX_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('ALEX_PRODUCTION', 'ModifierId', 'ALEX_PRODUCTION_MODIFIER');